### ISSUE TITLE
error processing sources/federal/fl-federal.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#45]
```
Downloading ftp://ftp.fgdl.org/pub/state/flma_mar16.zip
Returning ftp://ftp.fgdl.org/pub/state/flma_mar16.zip from local cache
Reading flma_mar16.zip
INFO:Fiona:Failed to auto identify EPSG: 7
Traceback (most recent call last):
  File "./Processing/process.py", line 77, in process
    source_filename=source.get("filenameInZip", None))
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/shp.py", line 40, in read
    collection = fiona_dataset.read_fiona(source, prop_map, filterer)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/fiona_dataset.py", line 66, in read_fiona
    feature['properties'], prop_map)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/property_transformation.py", line 28, in get_transformed_properties
    (source_value, key))
PropertyMappingFailedException: value:FNPNS not found in mapping for key:type
value:FNPNS not found in mapping for key:type
Error processing file sources/federal/fl-federal.json
```

**Comment by JesseCrocker** [comment]
Fixed by removing all NPS from this file, because it's included in NPS source
