### ISSUE TITLE
Error processing sources/federal/id-fed.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#46]
```
Processing sources/federal/id-fed.json
Downloading http://cloud.insideidaho.org/webApps/util/zip.ashx?fn=http://cloud.insideidaho.org/data/blm/RLTY_SMA_PUB_24K_POLY.shp
Returning http://cloud.insideidaho.org/webApps/util/zip.ashx?fn=http://cloud.insideidaho.org/data/blm/RLTY_SMA_PUB_24K_POLY.shp from local cache
Reading zip.ashx
INFO:Fiona:Failed to auto identify EPSG: 7
Traceback (most recent call last):
  File "./Processing/process.py", line 77, in process
    source_filename=source.get("filenameInZip", None))
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/shp.py", line 40, in read
    collection = fiona_dataset.read_fiona(source, prop_map, filterer)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/fiona_dataset.py", line 66, in read_fiona
    feature['properties'], prop_map)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/property_transformation.py", line 28, in get_transformed_properties
    (source_value, key))
PropertyMappingFailedException: value:HSTRCWTR not found in mapping for key:adminAgency
value:HSTRCWTR not found in mapping for key:adminAgency
Error processing file sources/federal/id-fed.json
```

**Comment by JesseCrocker** [comment]
Fixed
