### ISSUE TITLE
Error Processing sources/state/HI/hawaii-state-parks.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#51]
```
Downloading http://files.hawaii.gov/dbedt/op/gis/data/parkplys_n83.shp.zip
Returning http://files.hawaii.gov/dbedt/op/gis/data/parkplys_n83.shp.zip from local cache
Reading parkplys_n83.shp.zip
Traceback (most recent call last):
  File "./Processing/process.py", line 77, in process
    source_filename=source.get("filenameInZip", None))
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/shp.py", line 40, in read
    collection = fiona_dataset.read_fiona(source, prop_map, filterer)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/fiona_dataset.py", line 66, in read_fiona
    feature['properties'], prop_map)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/property_transformation.py", line 28, in get_transformed_properties
    (source_value, key))
PropertyMappingFailedException: value:None not found in mapping for key:type
value:None not found in mapping for key:type
Error processing file sources/state/HI/hawaii-state-parks.json
```

**Comment by JesseCrocker** [comment]
Same error is breaking sources/state/HI/hawaii-state-reserves.json
