### ISSUE TITLE
Error Processing sources/state/MD/md-dnr.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#53]
```
Downloading http://data.imap.maryland.gov/datasets/a5de633b6ebf450b94dcb08b519c3414_0.zip
Returning http://data.imap.maryland.gov/datasets/a5de633b6ebf450b94dcb08b519c3414_0.zip from local cache
Reading a5de633b6ebf450b94dcb08b519c3414_0.zip
Traceback (most recent call last):
  File "./Processing/process.py", line 77, in process
    source_filename=source.get("filenameInZip", None))
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/shp.py", line 40, in read
    collection = fiona_dataset.read_fiona(source, prop_map, filterer)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/adapters/fiona_dataset.py", line 66, in read_fiona
    feature['properties'], prop_map)
  File "/Users/jesse/projects/OpenBounds/PublicLands/Processing/property_transformation.py", line 28, in get_transformed_properties
    (source_value, key))
PropertyMappingFailedException: value:CEDNR not found in mapping for key:type
value:CEDNR not found in mapping for key:type
Error processing file sources/state/MD/md-dnr.json
```

**Comment by kdough03** [comment]
I'll try changing filter from regex to exact match.

**Comment by JesseCrocker** [comment]
Fixed
